### ISSUE TITLE
Can't run with no-new-privileges

### ISSUE THREAD

**Issue by DennisGaida** [vegardit/docker-gitea-act-runner#11]
Getting the error message `sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?` on startup when I try to run the container with the `no-new-privileges` option (`--security-opt=no-new-privileges:true`). Using the `vegardit/gitea-act-runner:latest` version obviously, since the other version uses `privileged: true`.

I try to do this for all containers and maybe this is something that could be taken into account for the DooD-version?

**Comment by wblew** [comment]
The docker image starts by default with the container user being 'act'. However, during startup, it sudo's from act to root, to manage the `act` user's `uid`, `gid`, and ownership and permissions within its `/data` volume. See this line: https://github.com/vegardit/docker-gitea-act-runner/blob/14e718454aadfe7487f1939e75655c45f81f719b/image/run.sh#L30

Given that, its likely not compatible with docker's `no-new-privileges` option.

Disclaimer: I am no expert on docker. This is my opinion based on 10 minutes of research into the `no-new-privileges` option.

**Comment by sebthom** [comment]
This is actually an unsolved issue in docker world. There are countless blog posts reasoning about it. All existing workarounds/solutions are either hacks and/or have limitations one way or another. [This](https://github.com/moby/moby/issues/7198) issue has been raised with Docker Inc. 9 years ago and was closed as a won't fix with a rather [non-practical solution](https://github.com/moby/moby/issues/7198#issuecomment-191990887). 

Besides setting uid/gid at container build time or running a container with `--user` which can majorly confuse the container's OS there is also this tool intended for non-production use https://github.com/boxboat/fixuid

**Comment by sebthom** [comment]
Additionally, for the docker-out-of-docker approach (`vegardit/gitea-act-runner:latest`), I don't see how this could be handled inside the container without sudo permissions:

https://github.com/vegardit/docker-gitea-act-runner/blob/14e718454aadfe7487f1939e75655c45f81f719b/image/run_fixids.sh#L36-L47

The container user must be part of the `docker` group with the same GID as on the host system, otherwise it cannot access the docker socket. Since the GID maybe different on each docker host system group membership must be adjusted dynamically inside the container.

**As a side note:** if you are so concerned about docker security that you require `no-new-privileges` you should not use the docker-out-of-docker approach at all as the act runner container can basically control the complete host through the docker socket, see https://gitea.com/gitea/act_runner/issues/167 You should only use it on a dedicated docker host that does nothing else than running act jobs and the act jobs should only execute trusted code.

**Comment by sebthom** [comment]
I also thought about the socket proxy as I am using it for another use case, but I think the ACL isn't fine grain enough. you can either turn a permission globally on or off, which means you still can mess with non-related containers running on the same host through the proxy. it misses the ability to specify filters based on container name patterns or labels so you can allow the runner only create/stop/start job containers.

**Comment by sebthom** [comment]
> Very insightful. I'm running about ~50 different containers with `no-new-privileges` just fine

to be fair, an act runner container is very different from a regular containerized app as it needs access to resources outside of it's container it isn't conceptually meant to access.

**Comment by sebthom** [comment]
> Maybe [gitea.com/gitea/act_runner/issues/170](https://gitea.com/gitea/act_runner/issues/170) might be an approach.

dind-rootless also needs to be run with `--privileged ` https://github.com/docker-library/docker/issues/291

> I'm not sure that running dockerd within the container is necessary for the DooD container

The DooD container does not run dockerd, it is only included in the DinD image.

---

I now changed the init script in a way that `sudo` is only executed if a uid/gid actually needs to be changed or the act user cannot read/write the docker socket and the docker group needs to be adjusted. 

Maybe this works in your environment with `no-new-privileges`.
